kind: pipeline
type: docker
name: lokal

cache:
  mount:
    - _build
    - deps

steps:
- name: test
  image: bitwalker/alpine-elixir-phoenix:1.13
  environment:
    TEST_DATABASE_URL: ecto://postgres:postgres@database/lokal_test
  commands:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - npm install --prefix assets
  - mix test

- name: build and publish
  image: plugins/docker
  settings:
    repo: shibaobun/lokal
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

services:
- name: database
  image: postgres:13
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
