version: '3'

services:
  cannery:
    build:
      context: .
    container_name: cannery
    environment:
      DATABASE_URL: "ecto://postgres:postgres@cannery-db/cannery"
      # generate a random base64 string 64 characters long, preferably not from a website
      SECRET_KEY_BASE: "change-me-to-something-random-this-is-really-important-change-it"
    ports:
      # do not expose this publically!
      # always host from behind a reverse proxy with a properly configured certificate
      - "4000:4000"
    restart: always
    depends_on:
      - cannery-db

  cannery-db:
    image: postgres:9.6
    container_name: cannery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cannery
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data