version: '3'

services:
  lokal:
    build:
      context: .
    container_name: lokal
    restart: always
    environment:
      - DATABASE_URL="ecto://postgres:postgres@lokal-db/lokal"
      # generate a random base64 string 64 characters long, preferably not from a website
      - SECRET_KEY_BASE="change-me-to-something-random-this-is-really-important-change-it"
    expose:
      - "4000"
    depends_on:
      - lokal-db

  lokal-db:
    image: postgres:13
    container_name: lokal-db
    restart: always
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_DB="lokal"
    volumes:
      - ./data:/var/lib/postgresql/data
